# Generated by Django 3.2.16 on 2025-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20250605_0711"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="destination",
            new_name="following",
        ),
        migrations.RenameField(
            model_name="follow",
            old_name="source",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
        ),
    ]
